/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchChannelIdRouteImport } from './routes/watch.$channelId'
import { Route as ApiCheckStreamRouteImport } from './routes/api/check-stream'
import { Route as ApiCatalogRouteImport } from './routes/api/catalog'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchChannelIdRoute = WatchChannelIdRouteImport.update({
  id: '/watch/$channelId',
  path: '/watch/$channelId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckStreamRoute = ApiCheckStreamRouteImport.update({
  id: '/api/check-stream',
  path: '/api/check-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogRoute = ApiCatalogRouteImport.update({
  id: '/api/catalog',
  path: '/api/catalog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favourites': typeof FavouritesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/check-stream': typeof ApiCheckStreamRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favourites': typeof FavouritesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/check-stream': typeof ApiCheckStreamRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/favourites': typeof FavouritesRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/catalog': typeof ApiCatalogRoute
  '/api/check-stream': typeof ApiCheckStreamRoute
  '/watch/$channelId': typeof WatchChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/favourites'
    | '/search'
    | '/sitemap.xml'
    | '/api/catalog'
    | '/api/check-stream'
    | '/watch/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/favourites'
    | '/search'
    | '/sitemap.xml'
    | '/api/catalog'
    | '/api/check-stream'
    | '/watch/$channelId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/favourites'
    | '/search'
    | '/sitemap.xml'
    | '/api/catalog'
    | '/api/check-stream'
    | '/watch/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  FavouritesRoute: typeof FavouritesRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCatalogRoute: typeof ApiCatalogRoute
  ApiCheckStreamRoute: typeof ApiCheckStreamRoute
  WatchChannelIdRoute: typeof WatchChannelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$channelId': {
      id: '/watch/$channelId'
      path: '/watch/$channelId'
      fullPath: '/watch/$channelId'
      preLoaderRoute: typeof WatchChannelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/check-stream': {
      id: '/api/check-stream'
      path: '/api/check-stream'
      fullPath: '/api/check-stream'
      preLoaderRoute: typeof ApiCheckStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalog': {
      id: '/api/catalog'
      path: '/api/catalog'
      fullPath: '/api/catalog'
      preLoaderRoute: typeof ApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  FavouritesRoute: FavouritesRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCatalogRoute: ApiCatalogRoute,
  ApiCheckStreamRoute: ApiCheckStreamRoute,
  WatchChannelIdRoute: WatchChannelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
